steps:
  # Step 1: Authenticate with Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Mkhsanjay@1997" | docker login -u "mukeshravi" --password-stdin

  # Step 2: Pull the private Docker image from Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker.io/mukeshravi/datahub_images:fe_image_latest']

options:
  logging: NONE


