---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker login --username=$$docker-username --password=$$docker-password
    secretEnv:
      - docker-username
      - docker-password
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker run $$docker-user/mukeshravi/datahub_images:fe_image_latest
    secretEnv:
      - docker-username
availableSecrets:
  secretManager:
    - versionName: projects/ardent-iris-389305/secrets/docker-password/versions/2
      env: docker-password
    - versionName: projects/ardent-iris-389305/secrets/docker-username/versions/1
      env: docker-username
options:
  logging: NONE

