---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker login -u $$docker-username -p $$docker-password
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:pgdb_image_latest
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:be_image_latest
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:fe_image_latest
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - me-central1-docker.pkg.dev/ardent-iris-389305/gcp-azure-pipeline/myimage
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker push
        me-central1-docker.pkg.dev/ardent-iris-389305/gcp-azure-pipeline/myimage
options:
  logging: NONE
