steps:
  # Step 1: Authenticate with Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Mkhsanjay@1997" | docker login -u "mukeshravi" --password-stdin hub.docker.com/layers/mukeshravi/datahub_images

  # Step 2: Pull the private Docker image from Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker.io/mukeshravi/datahub_images:fe_image_latest']

secrets:
  # Secret environment variables
  - name: 'mukeshravi'
    secretManager:
      versionName: 'projects/ardent-iris-389305/secrets/docker-username/versions/1'
  - name: 'Mkhsanjay@1997'
    secretManager:
      versionName: 'projects/ardent-iris-389305/secrets/docker-password/versions/1'

options:
  logging: NONE


