
---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/ardent-iris-389305/mukeshravi/datahub_images:fe_image_latest
      - https://hub.docker.com/layers/mukeshravi/datahub_images/fe_image_latest
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/ardent-iris-389305/mukeshravi/datahub_images:fe_image_lates
options:
  logging: NONE



