---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - echo $DOCKERHUB_PASSWORD | docker login -u $mukeshravi --password-stdin
    secretEnv:
      - mukeshravi
      - Mukesh@97
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - mukeshravi/datahub_images:fe_image_latest
  - name: gcr.io/cloud-builders/docker
    args:
      - run
      - --rm
      - mukeshravi/datahub_images:fe_image_latest



