---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker login --username="$$USERNAME" --password="$$PASSWORD"
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:pgdb_image_latest
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - me-central1-docker.pkg.dev/ardent-iris-389305/gcp-azure-pipeline/pg_datahub-image
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker push me-central1-docker.pkg.dev/ardent-iris-389305/gcp-azure-pipeline/pg_datahub-image
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:be_image_latest
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - me-central1-docker.pkg.dev/ardent-iris-389305/gcp-azure-pipeline/be_datahub-image
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker push me-central1-docker.pkg.dev/ardent-iris-389305/gcp-azure-pipeline/be_datahub-image
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:fe_image_latest
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - me-central1-docker.pkg.dev/ardent-iris-389305/gcp-azure-pipeline/fe_datahub-image
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker push me-central1-docker.pkg.dev/ardent-iris-389305/gcp-azure-pipeline/fe_datahub-image
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'datahub-pub-1', '--zone', 'us-east1-b', '--command', 'echo "Logged in to VM"']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'datahub-pub-1', '--zone', 'us-east1-b',  '--command', 'sudo apt-get -y autoremove && sudo apt-get update && sudo apt install -y apt-transport-https ca-certificates curl software-properties-common && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" && apt-cache policy docker-ce && sudo apt install -y docker-ce']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'datahub-pub-1', '--zone', 'us-east1-b', '--command', 'docker image pull us-central1-docker.pkg.dev/ardent-iris-389305/gcf-artifacts/fe_datahub-image']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'datahub-pub-1', '--zone', 'us-east1-b', '--command', 'docker image run -d -p 80:80 us-central1-docker.pkg.dev/ardent-iris-389305/gcf-artifacts/fe_datahub-image']
timeout: '600s' 
availableSecrets:
  secretManager:
  - versionName: projects/ardent-iris-389305/secrets/docker-password/versions/1
    env: 'PASSWORD'
  - versionName: projects/ardent-iris-389305/secrets/docker-username/versions/1
    env: 'USERNAME'
options:
  logging: CLOUD_LOGGING_ONLY
