 ---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker login --username=mukeshravi --password=Mukesh@97
    secretEnv:
      - mukeshravi
      - Mukesh@97
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker run mukeshravi/datahub_images:fe_image_latest
    secretEnv:
      - mukeshravi
availableSecrets:
  secretManager:
    - versionName: projects/ardent-iris-389305/secrets/docker-password/versions/2
      env: Mukesh@97
    - versionName: projects/ardent-iris-389305/secrets/docker-username/versions/1
      env: mukeshravi
options:
  logging: NONE
