---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker login --username=$$mukeshravi --password=$$Mukesh@97
    secretEnv:
      - mukeshravi
      - Mukesh@97
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker run $$mukeshravi/
    secretEnv:
      - mukeshravi
availableSecrets:
  secretManager:
    - versionName: projects/ardent-iris-389305/secrets/docker-password/1/1
      env: PASSWORD
    - versionName: projects/ardent-iris-389305/secrets/docker-username/1/1
      env: USERNAME
options:
  logging: NONE

