---
steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    entrypoint: bash
    args:
      - -c
      - >
        docker build -t us.gcr.io/${PROJECT_ID}/image_name --build-arg
        secret=$$SECRET .
    secretEnv:
      - SECRET
options:
  logging: NONE


